from sqlalchemy.orm import Session

from .models import SchoolProgram
from .services.query_schema import compose_query_output

SEED_SCHOOLS = [
    {
        "country": "美国",
        "school_name": "Carnegie Mellon University",
        "program_name": "MS in Computer Science",
        "major_track": "CS",
        "tuition_usd": 56000,
        "living_cost_usd": 24000,
        "ranking_score": 96,
        "median_salary_usd": 145000,
        "safety_score": 72,
        "course_difficulty": 9,
        "employment_support": 91,
        "visa_support": 74,
        "alumni_network": 93,
        "immigration_friendly": 58,
        "domestic_recognition": 95,
        "notes": "Top CS output, very high study pressure.",
    },
    {
        "country": "美国",
        "school_name": "Northeastern University",
        "program_name": "MS in Information Systems",
        "major_track": "IS",
        "tuition_usd": 43000,
        "living_cost_usd": 22000,
        "ranking_score": 82,
        "median_salary_usd": 115000,
        "safety_score": 80,
        "course_difficulty": 7,
        "employment_support": 90,
        "visa_support": 83,
        "alumni_network": 79,
        "immigration_friendly": 61,
        "domestic_recognition": 81,
        "notes": "Strong co-op and internship pathways.",
    },
    {
        "country": "美国",
        "school_name": "University of Southern California",
        "program_name": "MS in Applied Data Science",
        "major_track": "DS",
        "tuition_usd": 52000,
        "living_cost_usd": 26000,
        "ranking_score": 88,
        "median_salary_usd": 126000,
        "safety_score": 68,
        "course_difficulty": 8,
        "employment_support": 84,
        "visa_support": 76,
        "alumni_network": 90,
        "immigration_friendly": 57,
        "domestic_recognition": 89,
        "notes": "Large Chinese alumni network.",
    },
    {
        "country": "澳洲",
        "school_name": "The University of Melbourne",
        "program_name": "Master of Information Technology",
        "major_track": "IT",
        "tuition_usd": 36000,
        "living_cost_usd": 18000,
        "ranking_score": 90,
        "median_salary_usd": 90000,
        "safety_score": 86,
        "course_difficulty": 7,
        "employment_support": 79,
        "visa_support": 82,
        "alumni_network": 85,
        "immigration_friendly": 74,
        "domestic_recognition": 91,
        "notes": "Balanced option for ranking and migration.",
    },
    {
        "country": "澳洲",
        "school_name": "Monash University",
        "program_name": "Master of Data Science",
        "major_track": "DS",
        "tuition_usd": 33000,
        "living_cost_usd": 17000,
        "ranking_score": 84,
        "median_salary_usd": 85000,
        "safety_score": 83,
        "course_difficulty": 6,
        "employment_support": 75,
        "visa_support": 80,
        "alumni_network": 78,
        "immigration_friendly": 75,
        "domestic_recognition": 80,
        "notes": "Cost-performance option in Australia.",
    },
    {
        "country": "英国",
        "school_name": "Imperial College London",
        "program_name": "MSc Computing",
        "major_track": "CS",
        "tuition_usd": 49000,
        "living_cost_usd": 27000,
        "ranking_score": 94,
        "median_salary_usd": 105000,
        "safety_score": 78,
        "course_difficulty": 9,
        "employment_support": 84,
        "visa_support": 72,
        "alumni_network": 91,
        "immigration_friendly": 55,
        "domestic_recognition": 94,
        "notes": "Very high reputation and heavy workload.",
    },
    {
        "country": "英国",
        "school_name": "University of Manchester",
        "program_name": "MSc Advanced Computer Science",
        "major_track": "CS",
        "tuition_usd": 35000,
        "living_cost_usd": 18000,
        "ranking_score": 86,
        "median_salary_usd": 87000,
        "safety_score": 81,
        "course_difficulty": 7,
        "employment_support": 77,
        "visa_support": 70,
        "alumni_network": 82,
        "immigration_friendly": 54,
        "domestic_recognition": 83,
        "notes": "Good value among UK choices.",
    },
    {
        "country": "印度尼西亚",
        "school_name": "Binus University",
        "program_name": "Master in Computer Science",
        "major_track": "CS",
        "tuition_usd": 8500,
        "living_cost_usd": 7000,
        "ranking_score": 64,
        "median_salary_usd": 24000,
        "safety_score": 75,
        "course_difficulty": 5,
        "employment_support": 63,
        "visa_support": 62,
        "alumni_network": 65,
        "immigration_friendly": 60,
        "domestic_recognition": 46,
        "notes": "Lower cost option in SEA market.",
    },
]


def seed_schools(db: Session) -> None:
    count = db.query(SchoolProgram).count()
    if count > 0:
        return

    for row in SEED_SCHOOLS:
        payload = dict(row)
        payload["query_output_json"] = compose_query_output(payload, payload.get("query_output_json") or {})
        db.add(SchoolProgram(**payload))
    db.commit()
